language: node_js
node_js:
  - 8
branches:
  only: master
env:
  - EXTENSION_ID=kbbbjimdjbjclaebffknlabpogocablj

deploy:
  provider: script
  skip_cleanup: true
  script: npm run release
  on:
      branch: master
