language: node_js
node_js:
  - 7
branches:
  only: master
env:
  - EXTENSION_ID=kbbbjimdjbjclaebffknlabpogocablj

cache:
  directories:
  - $HOME/.npm-daily-version

deploy:
  provider: script
  skip_cleanup: true
  script: npm run release
  on:
      branch: master
