# Automatically create a new version/tag, if new commits are available since the last tag
name: Auto-tagger

on:
  schedule:
    - cron: '3 3 * * 3' # Every Wednesday at 3:03 AM

jobs:
  create-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          if [[ $(git tag -l --points-at HEAD) = "" ]]; then
            export VER=20$(npx daily-version)
            git tag $VER -m $VER
            git push origin $VER
          fi
